
name: Builder

on: push

jobs:

  build:
    name: Build the program
    runs-on: ubuntu-20.04

    steps:
      - name: Build
        run: |
          git clone -b main --single-branch https://github.com/MaximSelhanovich/Lab-C/tree/main/Lab1
          cd Lab-C/Lab1/ 
          make test 
          ./test < text_test.txt
