name: Builder

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: Ubuntu-20.04

    steps:
    - run: |
        git clone -b main --single-branch https://github.com/MaximSelhanovich/Lab-C
        cd Lab-C/Lab1/ 
        make Lab1_2_Test
        ./Lab1_2_Test 
