  
name: Builder

on:
  push:
    branches: [Lab1]

jobs:
  build:

    runs-on: Ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          cd Lab-C/Lab1/ 
          make Lab1_2_Test
          ./Lab1_2_Test 
        
  pre-commit:

    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: pre-commit/action@v2.0.0
