name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - uses: pre-commit/action@v2.0.0
name: c-linter

on: [pull_request]
jobs:
  c-linter:
    name: c-linter
    runs-on: ubuntu-latest
    steps:
      - name: c-linter
        uses: ArtificialAmateur/clang-tidy-action@master
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
